// Generated by gencpp from file main_node3/MsgTutorial.msg
// DO NOT EDIT!


#ifndef MAIN_NODE3_MESSAGE_MSGTUTORIAL_H
#define MAIN_NODE3_MESSAGE_MSGTUTORIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main_node3
{
template <class ContainerAllocator>
struct MsgTutorial_
{
  typedef MsgTutorial_<ContainerAllocator> Type;

  MsgTutorial_()
    : stamp()
    , data(0)
    , cor_data()  {
      cor_data.assign(0.0);
  }
  MsgTutorial_(const ContainerAllocator& _alloc)
    : stamp()
    , data(0)
    , cor_data()  {
  (void)_alloc;
      cor_data.assign(0.0);
  }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int32_t _data_type;
  _data_type data;

   typedef boost::array<double, 3>  _cor_data_type;
  _cor_data_type cor_data;





  typedef boost::shared_ptr< ::main_node3::MsgTutorial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_node3::MsgTutorial_<ContainerAllocator> const> ConstPtr;

}; // struct MsgTutorial_

typedef ::main_node3::MsgTutorial_<std::allocator<void> > MsgTutorial;

typedef boost::shared_ptr< ::main_node3::MsgTutorial > MsgTutorialPtr;
typedef boost::shared_ptr< ::main_node3::MsgTutorial const> MsgTutorialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main_node3::MsgTutorial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main_node3::MsgTutorial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace main_node3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'main_node3': ['/home/doylewhy/efficient/moveit/20191009ur5test5/src/main_node3/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::main_node3::MsgTutorial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main_node3::MsgTutorial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_node3::MsgTutorial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_node3::MsgTutorial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_node3::MsgTutorial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_node3::MsgTutorial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main_node3::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62d0714983fcbcdfa996a71eafe20f3a";
  }

  static const char* value(const ::main_node3::MsgTutorial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62d0714983fcbcdfULL;
  static const uint64_t static_value2 = 0xa996a71eafe20f3aULL;
};

template<class ContainerAllocator>
struct DataType< ::main_node3::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main_node3/MsgTutorial";
  }

  static const char* value(const ::main_node3::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main_node3::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"int32 data\n"
"float64[3] cor_data\n"
;
  }

  static const char* value(const ::main_node3::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main_node3::MsgTutorial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.data);
      stream.next(m.cor_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgTutorial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_node3::MsgTutorial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main_node3::MsgTutorial_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
    s << indent << "cor_data[]" << std::endl;
    for (size_t i = 0; i < v.cor_data.size(); ++i)
    {
      s << indent << "  cor_data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cor_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN_NODE3_MESSAGE_MSGTUTORIAL_H
